### PR TITLE
Update ExprTk library

### PR DESCRIPTION
**Pull request by ArashPartow**

### CODE REVIEW

**Comment by markschl** [comment]
Thank you for this PR. I have to admit that the bindings are a bit neglected, and I'm actually thinking about switching to a git submodule.
May I ask something related to ExprTk in general: I'm rather unfamiliar with the internal structure of the library and C++ isn't my the language I feel most at home. I wonder, whether I can allow the pointer to a heap-allocated `exprtk::expression` to be shared between threads. Specifically, I would need to be sure, that `exprtk::expression::value()` has no side-effects, since the Rust bindings allow non-mutable access to the wrapping method (so it may be called from different threads). I also assume that `symbol_table` methods like `variable_ref`, `stringvar_ref`, `variable_count`, `stringvar_count` and `vector_count` have no side-effects.

**Comment by ArashPartow** [comment]
>  I'm actually thinking about switching to a git submodule.

This would be the best approach.

-----------------------------------

> whether I can allow the pointer to a heap-allocated exprtk::expression to be shared between threads.

Consider the following two expressions:

1.  x+ 3
2.  y := x + 3

where x and y are variables derived from the symbol_table. The symbol_table holds references to actual variables found either on the stack or heap. So in neither scenario would it be thread-safe to call the experssions whilst mutating/changing the variables from different threads without the appropriate synchronisations. This is no difference in asking if it is ok to call a method of an instance of a class from different threads - same considerations have to be taken into account.

---------------------------------------

>  I also assume that symbol_table methods like variable_ref, stringvar_ref, variable_count, stringvar_count and vector_count have no side-effects.

They by themselves have no side-effects however in the case of variable_ref and stringvar_ref, you're essentially getting a reference - the code that gets the reference may make changes to those references, which would then cause side-effects.

**Comment by markschl** [comment]
Thanks for the answers. I wasn't thinking about the fact that formulas can actually modify the content of symbol tables :)

**Comment by markschl** [comment]
Switched to git submodule approach including the newest ExpTk version. New version released.

**Pull request closed without merging**
